services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: no
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "PGPASSWORD=${PG_PASSWORD} pg_isready -d ${PG_DATABASE} -h localhost -p 5432 -U ${PG_USER}"
      ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEF_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEF_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data: