name: CI Pipeline for the FastAPI Model Predictions app

on:
  push:
    branches: [class/MDPT]
    paths:
      - "Sem-VI/Modern-data-processing-technologies/Lab-06/**"
      - ".github/workflows/ci.yaml"
  pull_request:
    branches: [class/MDPT]
    paths:
      - "Sem-VI/Modern-data-processing-technologies/Lab-06/**"
      - ".github/workflows/ci.yaml"

jobs:
  build-and-test:
    name: Build and Test the application
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Sem-VI/Modern-data-processing-technologies/Lab-06

    steps:
      # --- Run the tests ---
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (v3.9)
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script (generate model + test data)
        run: python train.py

      - name: Run tests with pytest
        run: python -m pytest # Explicitly use 'python -m', since regular 'pytest' call failed during local testing

      # --- Build and push the container ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Sem-VI/Modern-data-processing-technologies/Lab-06
          file: ./Sem-VI/Modern-data-processing-technologies/Lab-06/Dockerfile
          push: true
          tags: mikeatta/fastapi-service:latest
